PRIVACY_VALIDATE_TOPIC = "privacy-validate-topic"
PRIVACY_VALIDATE_RESPONSE_TOPIC = "privacy-validate-response-topic"
PRIVACY_EXECUTE_TOPIC = "privacy-execute-topic"
PRIVACY_EXECUTE_RESPONSE_TOPIC = "privacy-execute-response-topic"

ALL_TOPICS = [
PRIVACY_VALIDATE_TOPIC,
PRIVACY_VALIDATE_RESPONSE_TOPIC,
PRIVACY_EXECUTE_TOPIC,
PRIVACY_EXECUTE_RESPONSE_TOPIC,
]